//
//  PhrasesList.swift
//  VoidNox
//
//  Created by Antonio Giordano on 17/04/23.
//

import Foundation

// A really really long set of quotes that were supposed to be about the story of your line, but after countless hours of research, i ended up reharsing the one i had previously collected, for a matter of time and sanity
let Quotes = [
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "And here's the start of the end of your journey, relax, the world is yours",
    "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
    "Nothing is impossible. The word itself says 'I'm possible! - Audrey Hepburn",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts- Winston Churchil",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The best way to predict the future is to create it.  - Peter Drucker",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.- Christian D. Larson" ,
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "The only thing standing between you and your goal is the story you keep telling yourself that you can't achieve it. - Jordan Belfort" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Spread love everywhere you go. - Mother Teresa",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
    "Always remember that you are absolutely unique. Just like everyone else. - Margaret Mead",
    "The only thing we have to fear is fear itself. - Franklin D. Roosevelt" ,
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller" ,
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "The only source of knowledge is experience. - Albert Einstein" ,
    "The only true way to happiness is to live in the present moment.  - Thich Nhat Hanh",
    "The only way to do great work is to be willing to fail. - Steve Jobs" ,
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "The best way to predict your future is to create it.  - Abraham Lincoln",
    "The only way to have a good day is to start it with a positive attitude.",
    "The only way to do great things is to love what you do. - Steve Jobs" ,
    "The only way to change the world is to be the change you wish to see. - Mahatma Gandhi",
    "The only way to have a life is to live it." ,
    "The only way to be truly happy is to do what you love." ,
    "The only way to achieve your dreams is to believe in yourself.",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt" ,
    "If you want to achieve greatness, stop asking for permission.",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt" ,
    "You are never too old to set another goal or to dream a new dream.  - C.S. Lewis",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson" ,
    "Believe in the power of your dreams and the world will change before your eyes.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The only way to do great work is to be passionate about what you do. - Steve Jobs",
    "Perseverance isn't useful without a strong will" ,
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi" ,
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The greatest wealth is to live content with little.  - Plato",
    "Perseverance isn't useful without a strong will",
    "When you reach the end of your rope, tie a knot in it and hang on. - Franklin D. Roosevelt" ,
]
